### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by dbalseiro** [plow-technologies/bs-Zarith#2]
This variable is not being used:
https://github.com/plow-technologies/bs-Zarith/blob/6c6eca6387f2335e40d846275fa1ba528f8676e9/src/Bigint.ml#L14

And can we add 
```
"warnings": {
  "error": "+A"
}
```
to `bsconfig.json` to treat all warnings as errors?

**Comment by mchaver** [comment]
Cool, I will add that.

**Comment by mchaver** [comment]
@dbalseiro 
Do you think removing warning `44` is ok?
```
  "warnings": {
    "number": "-44",
    "error": "+A"
  },
```
Otherwise it complains about all my tests, even though I am using opens.
```
  Warning number 44
  /home/james/work/plow/bs-Zarith/__tests__/bs_Bigint_test.ml 395:15-47
  
  393 ┆ 
  394 ┆ test "0 <> 1" (fun () ->
  395 ┆   expect @@ Bigint.((of_int 0) <> (of_int 1)) |> toEqual true);
  396 ┆ 
  397 ┆ test "gcd 2 12" (fun () ->
  
  this open statement shadows the value identifier <> (which is later used)
```

**Comment by dbalseiro** [comment]
Yes... I think it's a common pattern to leave the shadowing as warnings (I don't recall where I read it... but I did :smile:)
Maybe you can leave it as `"error": "+A-44"` that way the warning will still show

**Comment by mchaver** [comment]
Master has been updated and I've pushed the new version 1.0.1 to npm.
https://www.npmjs.com/package/bs-zarith
